development:
  secret_key_base: <%= ENV["APPLICATION_SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["APPLICATION_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["APPLICATION_SECRET_KEY_BASE"] %>
